=== BenjaminGuzman/login-monitor/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Config",
  "description": "Config for login-monitor",
  "type": "object",
  "required": ["sender", "recipient", "subject", "textMessage"],
  "properties": {
    "sender": {
      "description": "Sender's data",
      "type": "object",
      "required": [
        "email"
      ],
      "properties": {
        "email": "string",
        "pgpKeyId": "string"
      }
    },
    "recipient": {
      "description": "Recipient's data",
      "type": "object",
      "required": [
        "email"
      ],
      "properties": {
        "email": "string",
        "pgpKeyId": "string"
      }
    },
    "cc": {
      "description": "Carbon copy recipients data",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "email": "string",
          "pgpKeyId": "string"
        },
        "required": [
          "email"
        ]
      }
    },
    "attachments": {
      "type": "array",
      "items": "string"
    },
    "subject": "string",
    "textMessage": "string",
    "htmlMessage": "string",
    "senderPassFile": {
      "description": "Sender's private key passphrase file",
      "type": "string"
    }
  }
}

=== BenjaminGuzman/login-monitor/config-example.json
{
  "$schema": "https://raw.githubusercontent.com/BenjaminGuzman/login-monitor/master/schema.json",
  "sender": {
    "email": "bg@benjaminguzman.dev",
    "fakeSender": "fakesender@benjaminguzman.dev",
    "pgpKeyId": "bg@benjaminguzman.dev"
  },
  "recipient": {
    "email": "bg@benjaminguzman.dev",
    "pgpKeyId": "bg@benjaminguzman.dev"
  },
  "cc": [{
    "email": "benja@kobd.io",
    "pgpKeyId": "benja@kobd.io"
  }, {
    "email": "sysadmin@benjaminguzman.dev",
    "pgpKeyId": "0xFA427B996B631BDF"
  }],
  "subject": "New login on %h",
  "textMessage": "./message-example.txt",
  "htmlMessage": "./message-example.html",
  "senderPassFile": "private-passphrase.txt",
  "attachments": ["/var/log/audit"]
}
